server:
  port: 80
  servlet:
    context-path: /

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_user?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false&useUnicode=true
    username: root
    password: 88888888
  redis:
    host: 127.0.0.1
    port: 6379
    connect-timeout: 10s # 连接超时时间
    lettuce: # redis 客户端（默认 lettuce，还有 jedis）
      pool: # 连接池配置
        max-active: 8 # 最大连接数（负数表示没有限制）
        max-wait: 200s # 最大阻塞等待时间（负数表示没有限制，默认 -1）
        max-idle: 8 # 最大空闲连接
        min-idle: 0 # 最小空闲连接
  security:
    user:
      name: user
      password: 1

mybatis-plus:
  global-config:
    db-config:
      id-type: auto # 配置全局 id 自增
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名
    auto-mapping-behavior: full # 自动映射字段，包括复杂结果集
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启控制台 SQL 日志打印
  mapper-locations: classpath*:/mapper/**/*.xml